services:
  fastapi:
    image: "fastapi-service"
    stop_signal: SIGINT
    build:
      context: ./fastapi-service/src
    links:
      - pg-database
      - tg-bot
    stdin_open: true
    command: >
      sh -c "poetry run python3 -m main"
    ports:
      - "8000:8000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  pg_database:
    image: postgres:14-alpine
    container_name: "pg_database_game"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    container_name: "elasticsearch"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  pgdata: { }
  esdata:
