"""empty message

Revision ID: 15d970b43df7
Revises: 
Create Date: 2025-02-19 09:42:16.271566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d970b43df7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countrys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stadiums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('build_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countrys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('m_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('team1', sa.String(length=5), nullable=False),
    sa.Column('team2', sa.String(length=5), nullable=False),
    sa.Column('stadium_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('stadiums')
    op.drop_table('countrys')
    # ### end Alembic commands ###
