"""empty message

Revision ID: 2d7e163435d1
Revises: 
Create Date: 2025-02-18 16:31:56.794437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7e163435d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('m_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('team1', sa.String(length=5), nullable=False),
    sa.Column('team2', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stadium',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('build_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stadium')
    op.drop_table('game')
    # ### end Alembic commands ###
