"""empty message

Revision ID: 705e6f823eb6
Revises: 
Create Date: 2025-02-03 16:58:11.715200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705e6f823eb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('m_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('stadium', sa.String(length=20), nullable=False),
    sa.Column('team1', sa.String(length=5), nullable=False),
    sa.Column('team2', sa.String(length=5), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
