"""empty message

Revision ID: 9269056e48fc
Revises: b79be0e86f76
Create Date: 2025-02-18 16:42:48.463869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9269056e48fc'
down_revision: Union[str, None] = 'b79be0e86f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'games', ['id'])
    op.create_foreign_key(None, 'games', 'stadiums', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='unique')
    # ### end Alembic commands ###
