"""empty message

Revision ID: b76825cb3a4f
Revises: 9269056e48fc
Create Date: 2025-02-18 16:47:35.845393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76825cb3a4f'
down_revision: Union[str, None] = '9269056e48fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('stadium_id', sa.UUID(), nullable=False))
    op.drop_constraint('games_id_key', 'games', type_='unique')
    op.drop_constraint('games_id_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'stadiums', ['stadium_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_id_fkey', 'games', 'stadiums', ['id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('games_id_key', 'games', ['id'])
    op.drop_column('games', 'stadium_id')
    # ### end Alembic commands ###
