"""empty message

Revision ID: df2c75bc4a36
Revises: 2d7e163435d1
Create Date: 2025-02-18 16:39:29.690791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df2c75bc4a36'
down_revision: Union[str, None] = '2d7e163435d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('m_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('team1', sa.String(length=5), nullable=False),
    sa.Column('team2', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stadiums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('build_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stadium')
    op.drop_table('game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('m_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('team1', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('team2', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='game_pkey')
    )
    op.create_table('stadium',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('build_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stadium_pkey')
    )
    op.drop_table('stadiums')
    op.drop_table('games')
    # ### end Alembic commands ###
